"""featurize.py — algebraic featurizer for meta-model training data.

Computes structural features from ANY Cayley table (the permanent tool
from E9's pre-registration). Every future experiment contributes rows
to the meta-model dataset automatically.

Usage:
    from featurize import featurize_table
    feats = featurize_table(cayley_table, n)  # dict of named features
"""
import itertools


def find_identity(table, n):
    for e in range(n):
        if all(table[e][b] == b and table[b][e] == b for b in range(n)):
            return e
    return None


def element_order(table, n, a, identity):
    x, order = a, 1
    while x != identity:
        x = table[x][a]
        order += 1
        if order > n:
            return None  # not a group (no finite order)
    return order


def conjugacy_classes(table, n, identity):
    """Orbits under conjugation."""
    inverses = {}
    for a in range(n):
        for b in range(n):
            if table[a][b] == identity:
                inverses[a] = b
                break
    seen, classes = set(), []
    for a in range(n):
        if a in seen:
            continue
        cls = set()
        for b in range(n):
            conj = table[table[b][a]][inverses[b]]
            cls.add(conj)
        seen |= cls
        classes.append(sorted(cls))
    return classes


def commutator_subgroup(table, n, identity):
    """Elements expressible as a*b*a^-1*b^-1 (generators of [G,G])."""
    inverses = {}
    for a in range(n):
        for b in range(n):
            if table[a][b] == identity:
                inverses[a] = b
                break
    comm = set()
    for a in range(n):
        for b in range(n):
            c = table[table[a][b]][inverses[a]]
            c = table[c][inverses[b]]
            comm.add(c)
    # close under the operation (small groups: closure is quick)
    changed = True
    while changed:
        changed = False
        for a in list(comm):
            for b in list(comm):
                p = table[a][b]
                if p not in comm:
                    comm.add(p)
                    changed = True
    return comm


def center(table, n):
    """Elements commuting with everything."""
    z = []
    for a in range(n):
        if all(table[a][b] == table[b][a] for b in range(n)):
            z.append(a)
    return z


def faithful_perm_degree(table, n, identity):
    """Smallest set size on which G acts faithfully (lower bound via
    core-free subgroups; exact for small groups by checking subgroup
    actions). We compute: min over subgroups H of [G:H] where H is
    core-free (intersection of all conjugates is trivial). For small
    n we enumerate subgroup orbits cheaply via cyclic generation.
    """
    # enumerate subgroups generated by small subsets
    subs = set()
    for gens in itertools.chain.from_iterable(
            itertools.combinations(range(n), r) for r in range(0, min(n, 3) + 1)):
        H = {identity}
        changed = True
        while changed:
            changed = False
            for a in list(H):
                for g in gens:
                    for x in (table[a][g], table[g][a]):
                        if x not in H:
                            H.add(x)
                            changed = True
        if len(H) < n:
            subs.add(frozenset(H))
    if not subs:
        return n  # trivial action only
    inverses = {}
    for a in range(n):
        for b in range(n):
            if table[a][b] == identity:
                inverses[a] = b
                break
    best = n
    for H in subs:
        # core: intersection of all conjugates
        core = set(H)
        for g in range(n):
            conj = {table[table[g][h]][inverses[g]] for h in H}
            core &= conj
            if len(core) == 1:
                break
        if len(core) == 1:  # core-free -> faithful action of degree [G:H]
            best = min(best, n // len(H))
    return best


def featurize_table(table, n, name=None):
    """Full algebraic feature dict from a Cayley table."""
    identity = find_identity(table, n)
    if identity is None:
        return None
    orders = [element_order(table, n, a, identity) for a in range(n)]
    if any(o is None for o in orders):
        return None
    classes = conjugacy_classes(table, n, identity)
    comm = commutator_subgroup(table, n, identity)
    z = center(table, n)
    abelian = len(z) == n
    cyclic = len(set(orders)) <= 2 and max(orders) == n if abelian else False
    # cyclic check: some element has order n
    cyclic = any(o == n for o in orders)
    # irrep dims: for abelian, all 1; else compute from class sizes
    # (sum of squares of irrep dims = n; dims determined by class structure
    #  for the groups we use — full character table computation is heavier;
    #  we record class-size stats as proxies)
    class_sizes = sorted(len(c) for c in classes)
    exp = max(orders)
    feats = {
        "name": name,
        "order": n,
        "abelian": int(abelian),
        "cyclic": int(cyclic),
        "n_conjugacy_classes": len(classes),
        "n_comm_subgroup": len(comm),
        "center_size": len(z),
        "mean_element_order": sum(orders) / n,
        "max_element_order": max(orders),
        "distinct_element_orders": len(set(orders)),
        "exponent": exp,
        "max_class_size": max(class_sizes),
        "min_class_size": min(class_sizes),
        "faithful_perm_degree": faithful_perm_degree(table, n, identity),
        "abelian_order_ratio": len([o for o in orders if o == 1 or o == 2]) / n,
        # irrep proxies (exact for our groups):
        "n_irreps": len(classes),           # = # conjugacy classes
        "max_irrep_dim_sq": max(class_sizes),  # max dim^2 <= max class size bound
    }
    return feats


if __name__ == "__main__":
    import sys
    sys.path.insert(0, ".")
    from math_structures import STRUCTURES

    print("Featurizing all E7 structures:")
    for name, spec in STRUCTURES.items():
        table = spec["make"]()
        feats = featurize_table(table, spec["n"], name)
        print("  %-8s: %s" % (name, {k: v for k, v in feats.items()
                                     if k != "name"}))
