"""math_structures.py — Algebraic structure zoo for grokking-learnability
spectrum measurement.

THE EXPERIMENT: same order (8), same architecture, same training recipe,
only the Cayley table varies. Grokking difficulty becomes a direct
measurement of algebraic structure's effect on transformer learnability.

Groups (all order 8 unless noted):
  Z8       cyclic, abelian — (Z/8, +)
  Z4xZ2    abelian non-cyclic — (Z/4 × Z/2, +)
  Z2x2x2   elementary abelian — (Z/2)^3, XOR on 3 bits
  Q8       quaternion, non-abelian — {±1, ±i, ±j, ±k}
  D4       dihedral, non-abelian — symmetries of the square
  S3       symmetric on 3 elements, non-abelian (order 6, control)
  Z7       cyclic prime (order 7, control)

Each group is defined by its CAYLEY TABLE (n×n matrix of element indices).
All tables are verified: closure, identity, associativity (exhaustive for
order ≤ 8: 512 checks), inverses, and the expected abelian/cyclic status.
"""
import itertools
import torch


def cayley_from_op(op, n):
    """Build a Cayley table from a binary operation on {0..n-1}."""
    return [[op(a, b) for b in range(n)] for a in range(n)]


def verify_group(table, n, expect_abelian=None, expect_cyclic=None):
    """Exhaustive verification for small groups (n ≤ 8)."""
    # closure
    for a in range(n):
        for b in range(n):
            assert 0 <= table[a][b] < n, f"closure fail at ({a},{b})"
    # identity exists
    found_id = False
    for e in range(n):
        if all(table[e][b] == b and table[b][e] == b for b in range(n)):
            found_id = True
            identity = e
            break
    assert found_id, "no identity"
    # associativity: (a*b)*c == a*(b*c), all n^3 triples
    for a in range(n):
        for b in range(n):
            for c in range(n):
                assert table[table[a][b]][c] == table[a][table[b][c]], \
                    f"associativity fail at ({a},{b},{c})"
    # inverses
    for a in range(n):
        found_inv = False
        for b in range(n):
            if table[a][b] == identity and table[b][a] == identity:
                found_inv = True
                break
        assert found_inv, f"no inverse for element {a}"
    # abelian?
    abelian = all(table[a][b] == table[b][a] for a in range(n) for b in range(n))
    if expect_abelian is not None:
        assert abelian == expect_abelian, \
            f"abelian={abelian}, expected {expect_abelian}"
    # cyclic? (generated by a single element)
    cyclic = False
    for g in range(n):
        generated = set()
        x = g
        for _ in range(n):
            generated.add(x)
            x = table[x][g]  # x * g
        if len(generated) == n:
            cyclic = True
            break
    if expect_cyclic is not None:
        assert cyclic == expect_cyclic, \
            f"cyclic={cyclic}, expected {expect_cyclic}"
    return {"identity": identity, "abelian": abelian, "cyclic": cyclic}


# ── Group definitions ─────────────────────────────────────────────────

def make_Z8():
    return cayley_from_op(lambda a, b: (a + b) % 8, 8)

def make_Z4xZ2():
    """Z/4 × Z/2: elements encoded as 2*a + b where a ∈ Z/4, b ∈ Z/2."""
    def op(a, b):
        a1, a2 = a // 2, a % 2
        b1, b2 = b // 2, b % 2
        return ((a1 + b1) % 4) * 2 + ((a2 + b2) % 2)
    return cayley_from_op(op, 8)

def make_Z2x2x2():
    """(Z/2)^3: elements are 3-bit vectors, operation is XOR."""
    def op(a, b):
        return a ^ b  # XOR on 3-bit encoding is component-wise Z/2 add
    return cayley_from_op(op, 8)

def make_Q8():
    """Quaternion group: {1, -1, i, -i, j, -j, k, -k}.
    Encoding: 0=1, 1=-1, 2=i, 3=-i, 4=j, 5=-j, 6=k, 7=-k.
    Multiplication: i*j=k, j*k=i, k*i=j, i²=j²=k²=-1."""
    # Cayley table by index
    # Elements: 0=1, 1=-1, 2=i, 3=-i, 4=j, 5=-j, 6=k, 7=-k
    # i*j = k (2*4 = 6), j*i = -k (4*2 = 7)
    # j*k = i (4*6 = 2), k*j = -i (6*4 = 3)
    # k*i = j (6*2 = 4), i*k = -j (2*6 = 5)
    Q = {}
    # represent elements as (sign, axis) where axis ∈ {0=scalar, 1=i, 2=j, 3=k}
    def qmul(a, b):
        sa, ia = divmod(a, 2)  # sa: 0=+, 1=-; ia: 0=1, 1=i, 2=j, 3=k
        sb, ib = divmod(b, 2)
        # quaternion multiplication table for (ia, ib) -> (result_axis, sign_change)
        # (i, j) -> k, (j, k) -> i, (k, i) -> j
        # (j, i) -> -k, (k, j) -> -i, (i, k) -> -j
        # identity: (0, anything) = anything; (anything, 0) = anything
        sign = (sa + sb) % 2  # XOR of signs
        # axis multiplication:
        if ia == 0:
            raxis = ib
        elif ib == 0:
            raxis = ia
        elif ia == ib:
            raxis = 0
            sign ^= 1  # i*i = -1, j*j = -1, k*k = -1
        elif (ia, ib) in ((1, 2), (2, 3), (3, 1)):
            raxis = {1: 3, 2: 1, 3: 2}[(ia, ib) and {(1,2):3, (2,3):1, (3,1):2}[(ia,ib)]]
            # i*j=k: (1,2)->3, j*k=i: (2,3)->1, k*i=j: (3,1)->2
            if (ia, ib) == (1, 2): raxis = 3
            elif (ia, ib) == (2, 3): raxis = 1
            elif (ia, ib) == (3, 1): raxis = 2
            # sign stays positive for cyclic products
        else:  # anti-cyclic: (2,1), (3,2), (1,3) -> negative of the third axis
            pairs = {(2, 1): 3, (3, 2): 1, (1, 3): 2}
            raxis = pairs[(ia, ib)]
            sign ^= 1  # anti-cyclic products get a minus sign
        return sign * 4 + raxis * 2 + raxis  # just return the encoded value

    # Simpler: just hardcode the 8x8 Cayley table
    # Elements: 0=1, 1=-1, 2=i, 3=-i, 4=j, 5=-j, 6=k, 7=-k
    table = [
        [0, 1, 2, 3, 4, 5, 6, 7],  # 1
        [1, 0, 3, 2, 5, 4, 7, 6],  # -1
        [2, 3, 1, 0, 6, 7, 5, 4],  # i
        [3, 2, 0, 1, 7, 6, 4, 5],  # -i
        [4, 5, 7, 6, 1, 0, 2, 3],  # j
        [5, 4, 6, 7, 0, 1, 3, 2],  # -j
        [6, 7, 4, 5, 3, 2, 1, 0],  # k
        [7, 6, 5, 4, 2, 3, 0, 1],  # -k
    ]
    return table

def make_D4():
    """Dihedral group D4 (order 8): square vertex permutations.
    Verified from permutations of {0,1,2,3} that preserve square edges.
    Cayley table from permutation composition (verified: non-abelian,
    associative, identity, inverses)."""
    table = [
        [0, 1, 2, 3, 4, 5, 6, 7],
        [1, 0, 6, 7, 5, 4, 2, 3],
        [2, 3, 0, 1, 6, 7, 4, 5],
        [3, 2, 4, 5, 7, 6, 0, 1],
        [4, 5, 3, 2, 0, 1, 7, 6],
        [5, 4, 7, 6, 1, 0, 3, 2],
        [6, 7, 1, 0, 2, 3, 5, 4],
        [7, 6, 5, 4, 3, 2, 1, 0],
    ]
    return table

def make_S3():
    """Symmetric group on 3 elements (order 6). Elements are permutations
    encoded as tuples of (0, 1, 2) permutations."""
    perms = list(itertools.permutations(range(3)))
    idx_of = {p: i for i, p in enumerate(perms)}
    n = len(perms)

    def compose(s, t):
        """(sigma ∘ tau)(x) = sigma(tau(x)). Returns index of result."""
        result = tuple(perms[s][perms[t][x]] for x in range(3))
        return idx_of[result]

    def op(a, b):
        sa, sb = perms[a], perms[b]
        result = tuple(sa[sb[x]] for x in range(3))
        return idx_of[result]

    return cayley_from_op(op, 6)

def make_Z7():
    return cayley_from_op(lambda a, b: (a + b) % 7, 7)


# ── Registry ──────────────────────────────────────────────────────────

STRUCTURES = {
    "Z8":       {"make": make_Z8,     "n": 8, "abelian": True,  "cyclic": True},
    "Z4xZ2":    {"make": make_Z4xZ2,  "n": 8, "abelian": True,  "cyclic": False},
    "Z2x2x2":   {"make": make_Z2x2x2, "n": 8, "abelian": True,  "cyclic": False},
    "Q8":       {"make": make_Q8,     "n": 8, "abelian": False, "cyclic": False},
    "D4":       {"make": make_D4,     "n": 8, "abelian": False, "cyclic": False},
    "S3":       {"make": make_S3,     "n": 6, "abelian": False, "cyclic": False},
    "Z7":       {"make": make_Z7,     "n": 7, "abelian": True,  "cyclic": True},
}


def verify_all():
    """Verify every group definition exhaustively."""
    results = {}
    for name, spec in STRUCTURES.items():
        table = spec["make"]()
        n = spec["n"]
        assert len(table) == n and all(len(r) == n for r in table), \
            f"{name}: table size wrong"
        props = verify_group(table, n, spec["abelian"], spec["cyclic"])
        results[name] = props
        print(f"  {name:8s} (n={n}): identity={props['identity']} "
              f"abelian={props['abelian']} cyclic={props['cyclic']} ✓")
    print(f"  all {len(STRUCTURES)} groups verified")
    return results


def make_task(structure_name, train_frac=0.4, seed=0, device="cpu"):
    """Generate (a, b) -> a∘b classification data from the Cayley table.

    Returns dict of {train_x, train_y, test_x, test_y} — same convention
    as the lab's data.py.
    """
    spec = STRUCTURES[structure_name]
    table = spec["make"]()
    n = spec["n"]

    xs, ys = [], []
    for a in range(n):
        for b in range(n):
            xs.append([a, b])
            ys.append(table[a][b])
    x = torch.tensor(xs, dtype=torch.long)
    y = torch.tensor(ys, dtype=torch.long)

    g = torch.Generator().manual_seed(seed)
    perm = torch.randperm(x.shape[0], generator=g)
    n_train = int(round(train_frac * x.shape[0]))
    tr, te = perm[:n_train], perm[n_train:]
    return {"train_x": x[tr].to(device), "train_y": y[tr].to(device),
            "test_x": x[te].to(device), "test_y": y[te].to(device)}


if __name__ == "__main__":
    verify_all()
